project: 'pa-poc-mlspec-1'
region: 'us-west2'
bucket: 'pa-poc-mlspec-1'

pipeline_name: 'chicago-vertex-training-270924'
experiment_name: 'chicago_new'



bq_dataset_name: 'playground' 
bq_table_name: 'taxi_trips'
bq_location: 'US'

dataset_display_name: 'chicago-taxi-tips'


