feature {
  name: "trip_month"
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "trip_day"
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "trip_day_of_week"
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "trip_hour"
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "trip_seconds"
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "trip_miles"
  type: FLOAT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "payment_type"
  type: BYTES
  domain: "payment_type"
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "pickup_grid"
  type: BYTES
  domain: "pickup_grid"
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "dropoff_grid"
  type: BYTES
  domain: "dropoff_grid"
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "euclidean"
  type: FLOAT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "loc_cross"
  type: BYTES
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "tip_bin"
  type: INT
  bool_domain {
  }
  presence {
    min_fraction: 1.0
    min_count: 1
  }
  shape {
    dim {
      size: 1
    }
  }
}
feature {
  name: "community_name"
  value_count {
    min: 1
    max: 1
  }
  type: BYTES
  domain: "community_name"
  presence {
    min_count: 1
  }
}
feature {
  name: "total_arrests"
  value_count {
    min: 1
    max: 1
  }
  type: INT
  presence {
    min_count: 1
  }
}
string_domain {
  name: "payment_type"
  value: "Cash"
  value: "Credit Card"
  value: "Dispute"
  value: "Mobile"
  value: "No Charge"
  value: "Prcard"
  value: "Prepaid"
  value: "Unknown"
}
string_domain {
  name: "pickup_grid"
  value: "POINT(-87.5 41.7)"
  value: "POINT(-87.6 41.7)"
  value: "POINT(-87.6 41.8)"
  value: "POINT(-87.6 41.9)"
  value: "POINT(-87.6 42)"
  value: "POINT(-87.7 41.7)"
  value: "POINT(-87.7 41.8)"
  value: "POINT(-87.7 41.9)"
  value: "POINT(-87.7 42)"
  value: "POINT(-87.8 41.8)"
  value: "POINT(-87.8 41.9)"
  value: "POINT(-87.8 42)"
  value: "POINT(-87.9 42)"
}
string_domain {
  name: "dropoff_grid"
  value: "POINT(-87.5 41.7)"
  value: "POINT(-87.6 41.7)"
  value: "POINT(-87.6 41.8)"
  value: "POINT(-87.6 41.9)"
  value: "POINT(-87.6 42)"
  value: "POINT(-87.7 41.7)"
  value: "POINT(-87.7 41.8)"
  value: "POINT(-87.7 41.9)"
  value: "POINT(-87.7 42)"
  value: "POINT(-87.8 41.8)"
  value: "POINT(-87.8 41.9)"
  value: "POINT(-87.8 42)"
  value: "POINT(-87.9 42)"
}
string_domain {
  name: "community_name"
  value: "Albany Park"
  value: "Archer Heights"
  value: "Armour Square"
  value: "Ashburn"
  value: "Auburn Gresham"
  value: "Austin"
  value: "Avalon Park"
  value: "Avondale"
  value: "Belmont Cragin"
  value: "Beverly"
  value: "Bridgeport"
  value: "Brighton Park"
  value: "Burnside"
  value: "Calumet Heights"
  value: "Chatham"
  value: "Chicago Lawn"
  value: "Clearing"
  value: "Douglas"
  value: "Dunning"
  value: "East Garfield Park"
  value: "East Side"
  value: "Edgewater"
  value: "Edison Park"
  value: "Englewood"
  value: "Forest Glen"
  value: "Fuller Park"
  value: "Gage Park"
  value: "Garfield Ridge"
  value: "Grand Boulevard"
  value: "Greater Grand Crossing"
  value: "Hegewisch"
  value: "Hermosa"
  value: "Humboldt Park"
  value: "Hyde Park"
  value: "Irving Park"
  value: "Jefferson Park"
  value: "Kenwood"
  value: "Lake View"
  value: "Lincoln Park"
  value: "Lincoln Square"
  value: "Logan Square"
  value: "Loop"
  value: "Lower West Side"
  value: "McKinley Park"
  value: "Montclare"
  value: "Morgan Park"
  value: "Mount Greenwood"
  value: "Near North Side"
  value: "Near South Side"
  value: "Near West Side"
  value: "New City"
  value: "North Center"
  value: "North Lawndale"
  value: "North Park"
  value: "Norwood Park"
  value: "O\'Hare"
  value: "Oakland"
  value: "Portage Park"
  value: "Pullman"
  value: "Riverdale"
  value: "Rogers Park"
  value: "Roseland"
  value: "South Chicago"
  value: "South Deering"
  value: "South Lawndale"
  value: "South Shore"
  value: "Uptown"
  value: "Washington Heights"
  value: "Washington Park"
  value: "West Elsdon"
  value: "West Englewood"
  value: "West Garfield Park"
  value: "West Lawn"
  value: "West Pullman"
  value: "West Ridge"
  value: "West Town"
  value: "Woodlawn"
}
